# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc9da5da27d710e61499807ee2b63f0d998887ee930a3c7553507369c29f7d0530673e15331a05ea8b65ac7b7519b989dbee8be4cf7c26f8f196ceb2232d2d21

test:
  secret_key_base: 1168a3c6d6c53e7699cd5b95f856cc8e2fd5aef1777be35f6955f58e441585aad0994fa1be4941a7f2aefd3261c32a6c33fdb2ad264c54ff924b921f7ad6f21b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
