# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907c745445d39872cb9e73c3c535065eb6bebc3a1bcb140921a62812656f5c9f7229bd54523f6e54c8ad588bece4ff208a1540763c7c030db0727cef5ae7360a

test:
  secret_key_base: 038fcc715bb8e2b466dcba648fa3ab23a53f3248c1dd0c657a24022d9ebf370f2db91a7d2e558363a8ce02e9872eb8107bb0adb978701f2d0c4e2b0090d86613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
