# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97409a55b50784a50cc046655e7f1bf0c4fb124fd5f848107eecc8643cfda13163be82cfc00eea1d12684783a484e4c06619643974f544bb41f25d560b5994c9

test:
  secret_key_base: f64a08febb2119428d7ee1fa4694059ff3cbd6acbacd5a01927cba7493b0827e823bcb8e7fbf8714d9383a7cd7b05accdd4522dce8d01967f4c3cd743e402c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
